# Generated by Django 5.2.1 on 2025-05-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_spotifyaccesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spotifyRefreshToken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
