# Generated by Django 5.2.1 on 2025-05-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_spotifyrefreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='spotifyAccessToken',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='spotifyRefreshToken',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
