# Generated by Django 5.2.1 on 2025-05-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_spotifyaccesstoken_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genre",
            old_name="genreName",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="media",
            old_name="albumName",
            new_name="album_name",
        ),
        migrations.RenameField(
            model_name="media",
            old_name="artistName",
            new_name="artist_name",
        ),
        migrations.RenameField(
            model_name="media",
            old_name="genreName",
            new_name="genre",
        ),
        migrations.RenameField(
            model_name="media",
            old_name="typeOfMedia",
            new_name="media_type",
        ),
        migrations.RenameField(
            model_name="media",
            old_name="savedAt",
            new_name="saved_at",
        ),
        migrations.RenameField(
            model_name="media",
            old_name="spotifyMediaURI",
            new_name="spotify_uri",
        ),
        migrations.RenameField(
            model_name="preferencevector",
            old_name="genreName",
            new_name="genre",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="curveballEnjoyment",
            new_name="curveball_enjoyment",
        ),
        migrations.AlterField(
            model_name="user",
            name="displayName",
            field=models.CharField(db_column="displayName", max_length=100),
        ),
        migrations.RenameField(
            model_name="user",
            old_name="displayName",
            new_name="display_name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="lastUpdated",
            new_name="last_updated",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="spotifyAccessToken",
            new_name="spotify_access_token",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="spotifyRefreshToken",
            new_name="spotify_refresh_token",
        ),
        migrations.AlterField(
            model_name="user",
            name="spotifyUserId",
            field=models.CharField(
                db_column="spotifyUserId", max_length=100, unique=True
            ),
        ),
        migrations.RenameField(
            model_name="user",
            old_name="spotifyUserId",
            new_name="spotify_user_id",
        ),
        migrations.RenameField(
            model_name="userfeedback",
            old_name="feedbackAt",
            new_name="feedback_at",
        ),
        migrations.RenameField(
            model_name="userfeedback",
            old_name="isLiked",
            new_name="is_liked",
        ),
    ]
