# Generated by Django 5.2.1 on 2025-05-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_market_artist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
