# Generated by Django 5.2.2 on 2025-06-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_explicit_content_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_curveball',
            field=models.BooleanField(default=False),
        ),
    ]
