FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    sqlite3 \
    gcc \
    default-libmysqlclient-dev \
    pkg-config \
    build-essential \
    libssl-dev \
    libffi-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /backend/backendApps

COPY requirements.txt /backend/
RUN pip install --no-cache-dir -r /backend/requirements.txt

COPY . /backend/

CMD ["sh", "-c", "coverage run -m pytest && coverage report -m && sleep 600"]

